using System;
using System.Collections.Generic;
using System.Text;

namespace CookTime.REST_API_CompanyListModel
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using Newtonsoft.Json.Linq;
    /// <summary>
    /// Ths class creates an object for Company json files reading, when brought as a singly-list
    /// author Jose Antonio Espinoza.
    /// </summary>
    public partial class CompanyListModel
    {
        [JsonProperty("length")]
        public int Length { get; set; }

        [JsonProperty("head")]
        public Head Head { get; set; }

        [JsonProperty("last")]
        public Head Last { get; set; }
    }
    /// <summary>
    /// Ths class creates an object for everytime the reading method encounters a next in the json.
    /// author Jose Antonio Espinoza.
    /// </summary>
    public partial class Next
    {
        [JsonProperty("data")]
        public CookTime.REST_API_CompanyModel.Company Data { get; set; }

        [JsonProperty("next")]
        public Head NextNext { get; set; }
    }
    /// <summary>
    /// Ths class creates an object for everytime the reading method encounters a head in the json.
    /// author Jose Antonio Espinoza.
    /// </summary>
    public partial class Head
    {
        [JsonProperty("data")]
        public CookTime.REST_API_CompanyModel.Company Data { get; set; }

        [JsonProperty("next")]
        public Next Next { get; set; }
    }
    /// <summary>
    /// Ths class creates a company model everytime the key "data" is encountered, this for saving them into an array and be able to show them.
    /// author Jose Antonio Espinoza.
    /// </summary>
    public partial class Data
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("email")]
        public string Email { get; set; }

        [JsonProperty("number")]
        public int Number { get; set; }

        [JsonProperty("schedule")]
        public string Schedule { get; set; }

        [JsonProperty("logo")]
        public string Logo { get; set; }

        [JsonProperty("location")]
        public string Location { get; set; }

        [JsonProperty("posts")]
        public int Posts { get; set; }

        [JsonProperty("followers")]
        public JArray Followers { get; set; }

        [JsonProperty("following")]
        public JArray Following { get; set; }

        [JsonProperty("members")]
        public JArray Members { get; set; }

        [JsonProperty("recipe")]
        public JArray Recipes { get; set; }
    }
    
    public partial class CompanyListModel
    {
        /// <summary>
        /// Methods that converts a json file to an object type
        /// author Jose Antonio Espinoza.
        /// </summary>
        public static CompanyListModel FromJson(string json) => JsonConvert.DeserializeObject<CompanyListModel>(json, CookTime.REST_API_CompanyListModel.Converter.Settings);
    }

    public static class Serialize
    {
        /// <summary>
        /// Methods that converts an object type to a json file
        /// author Jose Antonio Espinoza.
        /// </summary>
        public static string ToJson(this CompanyListModel self) => JsonConvert.SerializeObject(self, CookTime.REST_API_CompanyListModel.Converter.Settings);
    }
    /// <summary>
    /// Autogenerated methods by Newtonsoft.json
    /// author Jose Antonio Espinoza.
    /// </summary>
    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }
        /// <summary>
        /// Creates unique instance of a string convert parser, that works on every list model.
        /// author Jose Antonio Espinoza.
        /// </summary>
        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}
