using System;
using System.Collections.Generic;
using System.Text;

namespace CookTime.REST_API_RecipeListModel
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using Newtonsoft.Json.Converters;
    /// <summary>
    /// Class made to convert a singly list into an object for json file reading methods
    /// author Jose Antonio Espinoza.
    /// </summary>
    public partial class RecipeListModel
    {
        [JsonProperty("length")]
        public int Length { get; set; }

        [JsonProperty("head")]
        public Head Head { get; set; }

        [JsonProperty("last")]
        public Head Last { get; set; }
    }
    /// <summary>
    /// Class that makes a new Object everytime the reader encounters next key
    /// author Jose Antonio Espinoza.
    /// </summary>
    public partial class Next
    {
        [JsonProperty("data")]
        public CookTime.REST_API_RecipeModel.Recipe Data { get; set; }

        [JsonProperty("next")]
        public Head NextNext { get; set; }
    }
    /// <summary>
    /// Class that makes a new object everytime the reader encounters head key
    /// author Jose Antonio Espinoza.
    /// </summary>
    public partial class Head
    {
        [JsonProperty("data")]
        public CookTime.REST_API_RecipeModel.Recipe Data { get; set; }

        [JsonProperty("next")]
        public Next Next { get; set; }
    }
    /// <summary>
    /// Class that turns into a Recipe object every data when it finds data key.
    /// author Jose Antonio Espinoza.
    /// </summary>
    public partial class Data
    {
      
        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("author")]
        public string Author { get; set; }

        [JsonProperty("type")]
        public string TypeOfDish { get; set; }

        [JsonProperty("servings")]
        public int Servings { get; set; }

        [JsonProperty("duration")]
        public string Duration { get; set; }

        [JsonProperty("time")]
        public string Time { get; set; }

        [JsonProperty("difficulty")]
        public int Difficulty { get; set; }

        [JsonProperty("diet")]
        public string Diet { get; set; }

        [JsonProperty("ingredients")]
        public string Ingredients { get; set; }

        [JsonProperty("steps")]
        public string Steps { get; set; }

        [JsonProperty("price")]
        public int Price { get; set; }

        [JsonProperty("image")]
        public string Image { get; set; }

        [JsonProperty("date")]
        public string Date { get; set; }

        [JsonProperty("rating")]
        public double Rating { get; set; }

        [JsonProperty("comments")]
        public string Comments { get; set; }


    }

        public partial class RecipeListModel
    {
        /// <summary>
        /// Methods that converts a json file to an object type
        /// author Jose Antonio Espinoza.
        /// </summary>
        public static RecipeListModel FromJson(string json) => JsonConvert.DeserializeObject<RecipeListModel>(json, CookTime.REST_API_RecipeListModel.Converter.Settings);
    }

    public static class Serialize
    {
        /// <summary>
        /// Methods that converts an object type into a json file
        /// author Jose Antonio Espinoza.
        /// </summary>
        public static string ToJson(this RecipeListModel self) => JsonConvert.SerializeObject(self, CookTime.REST_API_RecipeListModel.Converter.Settings);
    }
    /// <summary>
    /// Methods autogenerated by Newtonsoft.json
    /// author Jose Antonio Espinoza.
    /// </summary>
    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }
        /// <summary>
        /// Creates unique singleton instance of string parser.
        /// author Jose Antonio Espinoza.
        /// </summary>
        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}
