// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using CookTime.REST_API_Models;
//
//    var registrationModel = RegistrationModel.FromJson(jsonString);

namespace CookTime.REST_API_Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class RegistrationModel
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("age")]
        public string Age { get; set; }

        [JsonProperty("email")]
        public string Email { get; set; }

        [JsonProperty("password")]
        public string Password { get; set; }

        [JsonProperty("ischef")]
        public bool Chef
        {
            get; set;
        }

    public partial class RegistrationModel
    {
        public static RegistrationModel FromJson(string json) => JsonConvert.DeserializeObject<RegistrationModel>(json, CookTime.REST_API_Models.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this RegistrationModel self) => JsonConvert.SerializeObject(self, CookTime.REST_API_Models.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}

