// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using CookTime.REST_API_UserModel;
//
//    var userListModel = UserListModel.FromJson(jsonString);

namespace CookTime.REST_API_UserModel
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class UserListModel
    {
        [JsonProperty("length")]
        public long Length { get; set; }

        [JsonProperty("head")]
        public Head Head { get; set; }

        [JsonProperty("last")]
        public Head Last { get; set; }
    }

    public partial class Next
    {
        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("next")]
        public Head NextNext { get; set; }
    }

    public partial class Head
    {
        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("next")]
        public Next Next { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("password")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Password { get; set; }

        [JsonProperty("email")]
        public string Email { get; set; }

        [JsonProperty("age")]
        public long Age { get; set; }
    }

    public partial class UserListModel
    {
        public static UserListModel FromJson(string json) => JsonConvert.DeserializeObject<UserListModel>(json, CookTime.REST_API_UserModel.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this UserListModel self) => JsonConvert.SerializeObject(self, CookTime.REST_API_UserModel.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}